fix(server): use right TextFile interface path on FilesystemTextFile class
Jigsaw-Code/outline-server pull request #1275
Opened 2023-01-24 20:12 UTC by murka

2023-01-24 22:56 UTC, fortuna requested changes
Thanks for the fix!

2023-01-24 22:56 UTC, fortuna commented on src/shadowbox/infrastructure/filesystem_text_file.ts
> +import {TextFile} from '../infrastructure/text_file';
It's in the same directory:
```suggestion
import {TextFile} from './text_file';
```

2023-01-25 14:33 UTC, murka commented
Oops, my bad, I fixed it's.

2023-01-27 17:10 UTC, fortuna approved these changes

2023-01-27 17:11 UTC, merged