GCP: Move to the waiting page as soon as server creation is initiated
Jigsaw-Code/outline-server pull request #920
Opened 2021-06-08 20:26 UTC by bemasc

Currently, if the user starts server creation in GCP, they are stuck on the region picker page until server creation completes.  This takes a long time, and is different from DigitalOcean, where server creation is faster because it hasn't fully completed when the creation request returns.

This change makes the GCP behavior match the DigitalOcean behavior, by creating a `ManagedServer` object as soon as we know what the instance's ID will be.  This required various refactors to change which parties are responsible for server creation at what point in time.  This change also includes some small cleanups that improve parallelism and separation between DigitalOcean and GCP.

2021-06-08 20:39 UTC, fortuna requested changes
If you started a server creation, you are done. Clicking on create server again should take you to a fresh server creation.
If you want to follow the progress, you should click on the server being created, as it should be on the sidebar.

2021-06-14 16:03 UTC, bemasc commented
OK, done.  (This required a much bigger change.)

2021-06-14 17:31 UTC, fortuna requested changes
There's a lot going on in this PR. In particular, the creation logic chance the the way we handle locations. I recommend separating that. Let's have one PR just for the way we handle locations. Then one for the creation change. That will make the review go faster and derisk things.

This is a partial review. I need to take another look later.

2021-06-14 17:31 UTC, fortuna commented on src/server_manager/web_app/digitalocean_server.ts
> +  getCityName(): string {
This is not returning a name, but a message id. Please update the name to reflect that.

But that really ties the model to localization, which is an application concept. It violates the layering. Domain model shouldn't depend on App. Ideally this should be a city id.

We can make up our own city ids, or reuse an existing one. I don't know of a good standard for city ids. However, google has its own standard that is used in [Analytics](https://developers.google.com/analytics/devguides/collection/protocol/v1/geoid), [Ads targeting](https://developers.google.com/adwords/api/docs/appendix/geotargeting) and [visualization tools](https://support.google.com/datastudio/answer/9843174?hl=en).

We could reuse that. The translation strings could be mapped from the city id (`city-${id}`).

Another possibility is to make the city id be `${region_code}-${normalize english name}`, which may be more readable. Region code would be using [ISO3166-2](https://en.wikipedia.org/wiki/ISO_3166-2).

2021-06-14 17:31 UTC, fortuna commented on src/server_manager/model/gcp.ts
> +export const LOCATION_MAP: {[regionId: string]: Region} = {
Let's make this map be GcpRegionId -> city, region, country ids.
We will need the country codes for the flags.

2021-06-14 17:31 UTC, fortuna commented on src/server_manager/model/gcp.ts
> +  'europe-central2': new Region(['Warsaw', 'Poland', 'Europe']),
Remove Europe

2021-06-14 17:31 UTC, fortuna commented on src/server_manager/web_app/digitalocean_server.ts
> +export function GetCityId(slug: RegionId): string {
I think this shouldn't be exported anymore. We should expose generic city ids, not DO-specific city ids.

2021-06-14 17:31 UTC, fortuna commented on src/server_manager/web_app/gcp_account.ts
> +  async createServer(projectId: string, description: string, zoneId: string):
Revert to name, since that's what we call in the product

2021-06-14 17:31 UTC, fortuna commented on src/server_manager/web_app/gcp_account.ts
> +function makeInstanceName(): string {
Perhaps rename to `makeInstanceGcpName` to make is clearer that that's the GCP name, not the application name.

2021-06-14 17:31 UTC, fortuna commented on src/server_manager/web_app/gcp_account.ts
> +        result.push(new GcpServer(this.id, locator, instance.name, Promise.resolve(), this.apiClient));
Keep constructing the id here. It's the creator that can ensure unique ids. The instance shouldn't be creating its own id.

2021-06-14 17:31 UTC, fortuna commented on src/server_manager/web_app/gcp_server.ts
> +    super(`${accountId}:${locator.instanceId}`);
Revert the id constructor to be in the caller.

2021-06-14 17:31 UTC, fortuna commented on src/server_manager/web_app/gcp_server.ts
> +    await this.completion;
Why do you need to wait for completion?

2021-06-14 17:31 UTC, fortuna commented on src/server_manager/web_app/gcp_server.ts
> +    // never got a static IP.
Or when delete fails half-way

2021-06-14 18:29 UTC, fortuna requested changes
Some more comments

2021-06-14 18:29 UTC, fortuna commented on src/server_manager/cloud/gcp_api.ts
> +  async createInstance(projectId: string, zoneId: string, data: {}):
Add the return type.

2021-06-14 18:29 UTC, fortuna commented on src/server_manager/web_app/gcp_account.ts
> +      description: instance.description,
What is this description and why do we need it?

2021-06-14 18:29 UTC, fortuna commented on src/server_manager/web_app/gcp_account.ts
> +    const completion: Promise<void> = Promise.all([
This parallelization could be a separate PR too.

2021-06-14 18:29 UTC, fortuna commented on src/server_manager/cloud/gcp_api.ts
> +    return {
Let's return the operation. It simplifies the API, keeps this low level.
The caller can then extract the instance Id and call `this.computeEngineOperationZoneWait`.
It already has to wait on the promise anyway, so we are not gaining much returning this composite type.

2021-06-21 20:33 UTC, bemasc commented
Blocked on #926, which partly overlaps.

2021-06-25 20:51 UTC, bemasc commented
Closing in favor of #933

2021-06-25 20:51 UTC, closed without merging